# Generated by Django 4.1.2 on 2023-08-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbc_lib_app', '0002_libraryuser_qr_code_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryuser',
            name='stars',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
